# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
name: Run tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.rst"
      - ".github/workflows/*"
      - "!.github/workflows/test.yml"
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**.rst"
      - ".github/workflows/*"
      - "!.github/workflows/test.yml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
  workflow_dispatch:

env:
  ETCDCTL_API: "3"
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

jobs:
  # Run "pytest tests" for various Python versions
  pytest:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        include:
          # Test against old and new python, and traefik v2 and v3
          - python: "3.8"
            backend: file
            traefik-version: "v2.10.7"
          - python: "3.12"
            backend: file
            traefik-version: "v3.0.0-beta5"

          # Test each backend that requires a python client against a modern
          # version of python to ensure clients are compatible.
          - python: "3.12"
            backend: redis
            # redis-test-version is tied to ubuntu's package, so we only test
            # redis 6 currently while redis 7 is out, see
            # https://packages.ubuntu.com/jammy/redis-server
          - python: "3.12"
            backend: etcd
            etcd-test-version: "v3.4.29" # https://github.com/etcd-io/etcd/releases
          - python: "3.12"
            backend: consul
            consul-test-version: "1.17.2" # https://github.com/hashicorp/consul/releases (but omit v prefix)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade setuptools pip
          pip install -r dev-requirements.txt -e .

      - name: List Python dependencies
        run: |
          pip freeze

      - name: Add ./bin to PATH
        run: |
          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV

      - name: Install traefik
        run: |
          TRAEFIK_VERSION=
          if [[ ! -z "${{ matrix.traefik-version }}" ]]; then
            TRAEFIK_VERSION=--traefik-version=${{ matrix.traefik-version }}
          fi

          python -m jupyterhub_traefik_proxy.install --output=./bin ${TRAEFIK_VERSION}

          traefik version

      - name: Install consul
        if: matrix.backend == 'consul'
        run: |
          curl -L https://releases.hashicorp.com/consul/${{ matrix.consul-test-version }}/consul_${{ matrix.consul-test-version }}_linux_amd64.zip > consul.zip
          unzip consul.zip -d ./bin consul

          consul version

      - name: Install etcd
        if: matrix.backend == 'etcd'
        run: |
          curl -L https://github.com/etcd-io/etcd/releases/download/${{ matrix.etcd-test-version }}/etcd-${{ matrix.etcd-test-version }}-linux-amd64.tar.gz > etcd.tar.gz
          tar -xzf etcd.tar.gz -C ./bin --strip-components=1 --wildcards '*/etcd*'

          etcdctl version

      - name: Install redis
        if: matrix.backend == 'redis'
        run: |
          sudo apt-get -y install redis-server

      - name: Run tests
        run: |
          if [[ "${{ matrix.backend }}" == "file" ]]; then
            # select everything _but_ the KV store backend tests
            export PYTEST_ADDOPTS="-k 'not etcd and not consul and not redis'"
          else
            # select backend subset
            export PYTEST_ADDOPTS="-k ${{ matrix.backend }}"
          fi

          pytest

      - uses: codecov/codecov-action@v3
